services:
  mc-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    env_file:
      - ../.env
    environment:
      EULA: "TRUE"
      TYPE: ${MC_TYPE:-VANILLA}
      VERSION: ${MC_VERSION:-LATEST}
      ONLINE_MODE: ${MC_ONLINE_MODE:-FALSE}
      DIFFICULTY: ${MC_DIFFICULTY:-peaceful}
    ports:
      - ${MC_PORT:-25565}:25565
    volumes:
      - mc-server-data:/data
    restart: unless-stopped

volumes:
  mc-server-data:
